import Gizachew from "../Images/Developers/Gizachewu.jpg";
import Haylemeskel from "../Images/Developers/Haylemeskel.jpg";
import Nurhusen from "../Images/Developers/Nurhusen.jpg";
import Amanuel from "../Images/Developers/AmanMobile.jpg";
import Dagmawi from "../Images/Developers/Dagmawi.jpg";
import Dawit from "../Images/Developers/DawitSema.jpg";
import DagmawitNegash from "../Images/Developers/DagnawutNegash12.jpg";
import Haymanot from "../Images/Developers/Haymanot.jpg";
import Bezawit_A from "../Images/Developers/Bezawit_A.jpg";
import YonatanGetachew from "../Images/Developers/YonatanGetachew.jpg";
import AbelMekonen from "../Images/Developers/Abel_.jpg";
import DanielYilma from "../Images/Developers/DaneilYilma.jpeg";
import HananAb from "../Images/Developers/HananAb (2).jpeg";
import Amira from "../Images/Developers/Amira.jpg";
import Mqkda from "../Images/Developers/Makqida.jpg";
import YordanosH from "../Images/Developers/YordanosH.jpg";
import Daniel_Temesgen from "../Images/Developers/Daniel_Temesgen.jpg";
import Kitessa_Fikadu from "../Images/Developers/Kitessa_Fikadu.jpg";
import Zelalem_Legesse from "../Images/Developers/Zelalem_Legesse.jpg";
import Mistire_Daniel from "../Images/Developers/Mistire_Daniel.jpg";
import Bereket_Tsegaye from "../Images/Developers/Bereket_Tsegaye.jpg";
import Tsiyon_Gashaw from "../Images/Developers/Tsiyon_Gashaw.jpg";

export const developers = [
  {
    name: "Haylemeskel Haylemariam",
    role: "Founder & Software Developer",
    image: Haylemeskel,
    bio: "Founder of EcoFarmIQ and progHubs. Passionate about AI-driven solutions, team collaboration, and building impactful projects.",
    skills: [
      "Microservices",
      "Node.js",
      "Express.js",
      "MongoDB",
      "MySQL",
      "Python",
      "Machine Learning",
      "REST APIs",
      "Team Leadership",
    ],
    github: "https://www.github.com/Hayle-HB",
    linkedin: "https://www.linkedin.com/in/haylemeskel-haylemariam-b9212b298/",
    twitter: "https://x.com/Hayle_HB",
    email: "haylemeskelhaylemariam@gmail.com",
    telegram: "https://t.me/Hayle_HB",
    portfolio: "https://ecofarmiq.vercel.com",
  },
  {
    name: "Dagmawit Negash",
    role: "Backend Developer",
    image: DagmawitNegash,
    bio: "Passionate about building scalable website and mentoring junior developers.",
    skills: ["Python", "Node.js", "Django", "Mysql", "MongoDB", "Express.js"],
    github: "https://github.com/DagmawitN",
    linkedin:
      "https://www.linkedin.com/in/dagmawit-negash-1950a3304?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    twitter: "",
    email: "21dagmawitnegash@gmail.com",
    telegram: "https://t.me/Daginegash",
    portfolio: "https://github.com/Cam-Link/local-server",
  },
  {
    name: "Dagmawi Milkias",
    role: "FrontEnd Developer",
    image: Dagmawi,
    bio: "Highly Motivated and results-oriented Front-End Developer passionate about building responsive and visually engaging websites and web applications.Strong foundation in core web development principles and extensive experience working with leading JavaScript frameworks and libraries",
    skills: [
      "React",
      "TailwindCSS",
      "TypeScript",
      "Figma",
      "responsive design",
      "networking",
      "collaboration",
    ],
    github: "https://github.com/Dagi2004",
    linkedin: "https://linkedin.com/dagmawimilkias",
    twitter: "https://twitter.com/alexchen",
    email: "dagmawimilkias@gmail.com",
    telegram: "https://t.me/DagmawiDev",
    portfolio: "https://dagmawiimilkias.netlify.app/",
  },
  {
    name: "Haymanot Aweke",
    role: "UI/UX designer",
    image: Haymanot,
    bio: "A skilled UI/UX designer creating intuitive, user-centered digital experiences",
    skills: ["prototype", "Figma", "Wireframe", "User research"],
    GitHub: "https://github.com/hanabif",
    linkedin: "https://www.linkedin.com/in/haymanot-aweke?",
    twitter: " ",
    email: "haymanotaweke9@gmail.com",
    telegram: "https://t.me/Nanamicrush",
    portfolio:
      "https://www.figma.com/design/n2xiAlxoQuVe3sIkKCFADo/Haymanot-Aweke-portfolio?node-id=0-1&t=DsMjOvPqTI2RMr4g-1",
  },
  {
    name: "Gizachew Mohammed",
    role: "Backend Developer",
    image: Gizachew,
    bio: "Backend Developer passionate about building scalable APIs, optimizing databases, and integrating AI into backend solutions.",
    skills: [
      "Node.js",
      "Express.js",
      "MongoDB",
      "MySQL",
      "Python",
      "REST APIs",
    ],
    github: "https://github.com/gechjs",
    linkedin: "https://www.linkedin.com/in/gizachew-mohammed/",
    twitter: "https://twitter.com/GizachewMo50513",
    email: "gizachew980@gmail.com",
    telegram: "https://t.me/Gech192127",
    portfolio: "https://gizachewm.com",
  },
  {
    name: "Dawit Sema",
    role: "Mobile Developer",
    image: Dawit,
    bio: "Experienced in building scalable Flutter applications, AI automation, and backend systems. Passionate about mentoring and optimizing workflows.",
    skills: [
      "Flutter",
      "Dart",
      "React",
      "TailwindCSS",
      "TypeScript",
      "Python",
      "Automation",
      "Django",
      "n8n",
      "Make.com",
    ],
    github: "https://github.com/DawitSema",
    linkedin: "https://linkedin.com/in/DawitSema",
    twitter: "https://twitter.com/DawitSema",
    email: "dawitsema2004@gmail.com",
    telegram: "https://t.me/DawitSema",
    portfolio: "https://dawitsema.vercel.app/",
  },
  {
    name: "Bezawit Yehalem",
    role: "UI/UX designer",
    image: Bezawit_A,
    bio: "Passionate about building scalable applications and mentoring junior developers.",
    skills: ["Figma", "Prototype", "Wireframe", "React", "TailwindCSS"],
    github: "https://github.com/bezu3007",
    linkedin: "https://www.linkedin.com/in/bezawit-yehalem",
    twitter: "",
    email: "bezayayi@gmail.com",
    telegram: "https://t.me/bezu3022",
    portfolio: "",
  },
  {
    name: "Nurhusen mohammedteum",
    role: "Frontend Developer",
    image: Nurhusen,
    bio: "Fullstack developer specialized on frontend development Passionate about building scalable applications and mentoring junior developers.",
    skills: [
      "React",
      "Next.js",
      "TypeScript",
      "Node.js",
      "Express.js",
      "MongoDB",
      "Javascript",
      "MySql",
    ],
    github: "https://github.com/nurhussenm",
    linkedin: "https://www.linkedin.com/in/nurhusenm",
    twitter: "https://x.com/NURHussenM74947",
    email: "mohammedteumnurhusen@gmail.com",
    telegram: "https://t.me/NUMUTU",
    portfolio: "https://nurhussen.netlify.app",
  },
  {
    name: "Amanuel Yosef",
    role: "Mobile App Developer",
    image: Amanuel,
    bio: "Freelance Mobile App Developer | Crafting beautiful, user-friendly apps with Kotlin, Jetpack Compose & Firebase. Let's turn your app idea into reality! DM for collaborations.",
    skills: ["Kotlin", "Jetpack compose", "Python", "Flutter"],
    github: "https://github.com/amanuelyosef",
    linkedin: "https://www.linkedin.com/in/amanuel-yosef-ab2685333/",
    twitter: "https://x.com/AmanuYosi",
    email: "amanuyosi@gmail.com",
    telegram: "https://t.me/proaman777",
  },
  {
    name: "Yonatan Getachew",
    role: "Machine Learning Engineer",
    image: YonatanGetachew,
    bio: "Seeing the future to AGI and building cool things to reach out there.",
    skills: [
      "LLM",
      "DeepLearning",
      "Anomaly Detection",
      "Reinforcement Leraning",
    ],
    github: "https://github.com/jajos12",
    linkedin: "https://linkedin.com/yonatangetachew98a789245",
    twitter: "https://twitter.com/alexchen",
    email: "yonatangetachew91@gmail.com",
    telegram: "https://t.me/jajos77",
  },
  {
    name: "Abel Mekonen",
    role: "Full Stack Developer",
    image: AbelMekonen,
    bio: "Passionate about building helpful and useful applications",
    skills: ["React", "Django", " MySQL", "Javascript"],
    github: "https://github.com/bella-247",
    linkedin: "https://www.linkedin.com/in/abel-mekonen-89b57b323",
    twitter: "",
    email: "abelmekonen247@gmail.com",
    telegram: "https://t.me/ydkbellathelatest",
    portfolio: "",
  },
  {
    name: "Daniel Yilma",
    role: "Backend Developer",
    image: DanielYilma,
    bio: "Passionate backend developer.",
    skills: ["Flask", "Django", "Node.js"],
    github: "https://github.com/Danielyilma",
    linkedin: "https://www.linkedin.com/in/daniel-yilma-858135256/",
    twitter: "https://x.com/DanielYilm66671",
    email: "deathland2352@gmail.com",
    telegram: "https://t.me/Daniy2r4",
    portfolio: "",
  },
  {
    name: "Hanan Abdulshikur",
    role: "Frontend Developer",
    bio: "Passionate Frontend Developer creating user-friendly, responsive web applications with a focus on design and functionality.",
    skills: ["React", "tailwind", "next.js", "shadcn"],
    github: "https://github.com/devhan-hub",
    linkedin: "https://www.linkedin.com/in/hanan-abdulshikur/",
    twitter: "",
    email: "hanabduman@gmail.com",
    telegram: "https://t.me/hanuninaaa",
    image: HananAb,
  },
  {
    name: "Amira Abdurahman",
    role: "Frontend Developer",
    image: Amira,
    bio: "Passionate about crafting responsive, user-friendly websites that merge clean code with sleek design",
    skills: ["React", "Node.js", "TypeScript", "AWS"],
    github: "https://github.com/ami798",
    linkedin: "https://www.linkedin.com/in/amira-abdurahman-282704298/",
    twitter: "https://x.com/amiprin7",
    email: "amiraabdurahman8@gmail.com",
    telegram: "https://t.me/amiprin7",
  },
  {
    name: "Mqkda Yoseph",
    role: "Full Stack Developer",
    bio: "Passionate about building scalable applications and mentoring junior developers.",
    skills: ["React", "Node.js", "Dart", "Flutter"],
    github: "https://github.com/Makda-Yoseph",
    linkedin:
      "https://www.linkedin.com/in/makda-zewge-08b145289?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    twitter: "",
    email: "makdayosephzewge@gmail.com",
    telegram: "https://t.me/makl-da",
    image: Mqkda,
  },
  {
    name: "Yordanos Hailu",
    role: "UI/UX designer",
    bio: "Dedicated to creating user-centered designs that enhance user experience.",
    skills: ["Figma", "Wireframe", "Prototyping", "User Centric Design"],
    linkedin: "https://www.linkedin.com/in/yordanos-hailu/",
    email: "yordiih59@gmail.com",
    telegram: "https://t.me/yordih00",
    portfolio: "https://dribbble.com/yordiHailu",
    twitter: "",
    github: "",
    image: YordanosH,
  },
  {
    name: "Daniel Temesgen",
    role: "Fullstack Developer",
    image: Daniel_Temesgen,
    bio: "hello new world.",
    skills: [
      "Node.js",
      "Javascript",
      "Tailwind",
      "PHP",
      "React",
      "NextJs",
      "SQL",
      "MongoDB",
    ],
    github: "https://github.com/hope-dies-here",
    linkedin: "https://www.linkedin.com/in/daniel-temesgen-a560b2353",
    twitter: "https://twitter.com/",
    email: "onyourleftpal@gmail.com",
    telegram: "https://t.me/o_uranus",
    portfolio: "https://dannny-pf.netlify.app",
  },
  {
    name: "Kitessa Fikadu",
    role: "Backend Developer",
    bio: "Passionate about building scalable backend and AI-driven solutions.",
    skills: [
      "FastAPI",
      "Django",
      "NestJS",
      "Gin",
      "Clean Architecture",
      "Microservices",
      "Machine Learning",
    ],
    github: "https://github.com/kitessafikadu",
    linkedin: "https://linkedin.com/kitessafikadu",
    twitter: "https://twitter.com/kitessafikadu",
    email: "kitessafikadu@gmail.com",
    telegram: "https://t.me/kitessafikadu",
    image: Kitessa_Fikadu,
  },
  {
    name: "Zelalem Legesse",
    role: "Full Stack Developer",
    bio: "A passionate Full stack developer building high-performance, scalable, and user-friendly web applications.",
    skills: [
      "Node.js",
      "Express.js",
      "MongoDB",
      "JavaScript",
      "React",
      "GitHub",
      "Git",
      "REST API",
      "PostgreSQL",
      "Authentication",
    ],
    github: "https://github.com/zelalem888",
    linkedin: "https://www.linkedin.com/in/zelalemlegesse/",
    twitter: "https://x.com/ZelalemLegess13",
    email: "legessezelalem888@gmail.com",
    telegram: "https://t.me/Zlelew",
    portfolio: "https://zelalemportfolio.vercel.app/",
    image: Zelalem_Legesse,
  },
  {
    name: "Abedela Bedru",
    role: "Full Stack Developer",
    bio: "Curious mind. Disciplined soul. I build, I grow, and I never settle.",
    skills: [
      "JavaScript",
      "React",
      "Node.js",
      "ExpressJS",
      "MongoDB",
      "EJS",
      "HTML",
      "CSS",
    ],
    github: "https://github.com/codistiano",
    linkedin: "https://linkedin.com/in/abedela-bedru",
    twitter: "https://twitter.com/codistiano",
    email: "codistiano@gmail.com",
    telegram: "https://t.me/codistiano",
    portfolio: "https://codistiano.vercel.app/",
    image: false,
  },
  {
    name: "Mistire Daniel",
    role: "Backend Developer",
    bio: "Aspiring Junior Software Developer.",
    skills: ["Python", "Django", "Javascript", "Git/Github"],
    github: "https://github.com/Mistire",
    linkedin: "https://www.linkedin.com/in/mistire-daniel-87b451229/",
    twitter: "https://x.com/Mistire37",
    email: "mistiredan@gmail.com",
    telegram: "https://t.me/therealmistire",
    portfolio: "",
    image: Mistire_Daniel,
  },
  {
    name: "Bereket Tsegaye",
    role: "Full Stack Developer",
    bio: "A passionate Full stack developer building high-performance, scalable, and user-friendly web applications.",
    skills: [
      "Node.js",
      "Express.js",
      "MongoDB",
      "JavaScript",
      "React",
      "Git",
      "REST API",
      "PostgreSQL",
      "Authentication",
    ],
    github: "https://github.com/treehouseapps",
    linkedin: "https://www.linkedin.com/in/berekettsegaye/",
    twitter: "https://x.com/Bereket54467899",
    email: "bbekijunior1@gmail.com",
    telegram: "https://t.me/B_smile",
    portfolio: "https://bekijunior.vercel.app/",
    image: Bereket_Tsegaye,
  },
  {
    name: "Tsiyon Gashaw",
    role: "Backend Developer | Mobile App Enthusiast",
    bio: "Driven by impact, I craft clean backend systems and sleek mobile apps — blending logic and design to solve real-world problems.",
    skills: ["Django", "Flutter", "RestApi", "Figma"],
    github: "https://github.com/tsitiii",
    linkedin: "https://www.linkedin.com/in/tsiyon-gashaw-0b12b92a0",
    twitter: "https://x.com/zitiii9",
    email: "tsiyong8@gmail.com",
    telegram: "https://t.me/Yok_submissive",
    portfolio: "http://tsiyongashaw.netlify.app/",
    image: Tsiyon_Gashaw,
  },
  {
    name: "Samuel Girma",
    role: "FrontEnd Developer",
    image: false,
    bio: "Passionate about building responsive and user-friendly web.",
    skills: ["React", "TailwindCSS", "next js"],
    github: "https://github.com/Sam44556",
    linkedin: "https://www.linkedin.com/in/samuel-girma-28046a299",
    twitter: "",
    email: "samuegirma875@gmail.com",
    telegram: "https://t.me/Trea357",
    portfolio: "",
  },
];
